# Generated by Django 4.2.1 on 2023-06-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_tag_alter_article_options_articlescope_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Тег"),
        ),
    ]
